# Generated by Django 3.2.16 on 2024-08-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='following',
        ),
    ]
